/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Random;
import java.awt.Graphics;
import java.awt.Color;
/**
 *
 * @author Zaid
 */
public class NewJFrame extends javax.swing.JFrame {
int num =11;


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jButton1.setText("RANDOM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("1.VERTEX");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("2.VERTEX");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("3.VERTEX");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("4.VERTEX");

        jTextField2.setText("34");

        jButton2.setText("ROTATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("5.VERTEX");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("6.VERTEX");

        jTextField1.setText("2");

        jTextField3.setText("0");

        jTextField4.setText("0");

        jTextField5.setText("0");

        jTextField6.setText("2");

        jTextField7.setText("0");

        jTextField8.setText("0");

        jTextField9.setText("0");

        jTextField10.setText("1");

        jButton3.setText("SACLE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton12);
        jRadioButton12.setText("7.VERTEX");

        buttonGroup2.add(jRadioButton13);
        jRadioButton13.setText("8.VERTEX");

        buttonGroup2.add(jRadioButton14);
        jRadioButton14.setText("9.VERTEX");

        buttonGroup2.add(jRadioButton15);
        jRadioButton15.setText("10.VERTEX");

        buttonGroup2.add(jRadioButton16);
        jRadioButton16.setText("11.VERTEX");

        jButton4.setText("MOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setText("PROJECTION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("PROPORTIONAL SCALING");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton5)
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jRadioButton6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton14, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jRadioButton13))
                                            .addGap(118, 118, 118))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jRadioButton15)
                                            .addGap(112, 112, 112))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton12)
                                        .addGap(64, 64, 64)
                                        .addComponent(jButton5)
                                        .addGap(20, 20, 20)
                                        .addComponent(jButton6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton2)
                                                    .addComponent(jRadioButton1))
                                                .addGap(55, 55, 55)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                                    .addComponent(jTextField1)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jRadioButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField6))
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                    .addComponent(jTextField9)
                                                    .addComponent(jTextField10))))))
                                .addGap(0, 29, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton2)
                                    .addGap(0, 13, Short.MAX_VALUE)))
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jRadioButton3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2)
                                            .addComponent(jButton4))))
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButton12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6))
                                .addGap(13, 13, 13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(jRadioButton13)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton14)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int [] [] Vertices =new int [11] [2];
public static int cX,cY;


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Random val = new Random();
        cX = jPanel1.getWidth() / 2;
        cY = jPanel1.getHeight() / 2;
        for(int i = 0 ; i<num ; i++){
            Vertices[i][0] = cX - val.nextInt(jPanel1.getWidth());  
            Vertices[i][1] = cY - val.nextInt(jPanel1.getHeight()); 
            
        }
        DrawObject();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
int i=0;
if(jRadioButton1.isSelected()) i=0;
if(jRadioButton2.isSelected()) i=1;
if(jRadioButton3.isSelected()) i=2;
if(jRadioButton4.isSelected()) i=3;
if(jRadioButton5.isSelected()) i=4;
if(jRadioButton6.isSelected()) i=5;
if(jRadioButton12.isSelected()) i=6;
if(jRadioButton13.isSelected()) i=7;
if(jRadioButton14.isSelected()) i=8;
if(jRadioButton15.isSelected()) i=9;
if(jRadioButton16.isSelected()) i=10;
Vertices[i][0] = evt.getX() - cX;
        Vertices[i][1] = cY - evt.getY();
        
DrawObject();

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       double a = Math.toRadians(Double.parseDouble(jTextField1.getText()));
       double b = Math.toRadians(Double.parseDouble(jTextField3.getText()));
       double c = Math.toRadians(Double.parseDouble(jTextField5.getText()));
       double d = Math.toRadians(Double.parseDouble(jTextField6.getText()));
        int n=11; 
        if(jRadioButton1.isSelected()) n=0;
        if(jRadioButton2.isSelected()) n=1;
        if(jRadioButton3.isSelected()) n=2;
        if(jRadioButton4.isSelected()) n=3;
        if(jRadioButton5.isSelected()) n=4;
        if(jRadioButton6.isSelected()) n=5;
        if(jRadioButton12.isSelected()) n=6;
        if(jRadioButton13.isSelected()) n=7;
        if(jRadioButton14.isSelected()) n=8;
        if(jRadioButton15.isSelected()) n=9;
        if(jRadioButton16.isSelected()) n=10;
        
        for (int i=0;i<num;i++){
           // double xn = Math.cos(alfa)*(Vertices[i][0]-Vertices[n][0]) - Math.sin(alfa)*(Vertices[i][1]Vertices[n][1]);
            //double yn = Math.sin(alfa)*(Vertices[i][0]-Vertices[n][0]) + Math.cos(alfa)*(Vertices[i][1]Vertices[n][1]);
            double xn = Math.cos(a)*(Vertices[i][0]-Vertices[n][0])  - Math.sin(b)*(Vertices[i][1]-Vertices[n][1]); 
            double yn = Math.sin(c)*(Vertices[i][0]-Vertices[n][0])  + Math.cos(d)*(Vertices[i][1]-Vertices[n][1]);
            Vertices[i][0] = (int)Math.round(xn) + Vertices[n][0];
            Vertices[i][1] = (int)Math.round(yn) + Vertices[n][1];
            
        
        }
        DrawObject();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       double a = Math.toRadians(Double.parseDouble(jTextField1.getText()));
       double b = Math.toRadians(Double.parseDouble(jTextField3.getText()));
       double c = Math.toRadians(Double.parseDouble(jTextField5.getText()));
       double d = Math.toRadians(Double.parseDouble(jTextField6.getText()));
       
      
        
        for (int i=0;i<num;i++){
            double xn = a*(Vertices[i][0])  + b*(Vertices[i][1]); 
            double yn = c*(Vertices[i][0])  + d*(Vertices[i][1]);
            Vertices[i][0] = (int)Math.round(xn) + Vertices[i][0];
            Vertices[i][1] = (int)Math.round(yn) + Vertices[i][1];
        
        }
        DrawObject();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       

      double e=Integer.parseInt(jTextField4.getText());
       double f=Integer.parseInt(jTextField7.getText());
       
      
        
        for (int i=0;i<num;i++){
            double xn = 0; 
            double yn = 0;
            Vertices[i][0] = (int)Math.round(xn) + Vertices[i][0]+(int)f;
            Vertices[i][1] = (int)Math.round(yn) + Vertices[i][1]+(int)e;
        
        }
        DrawObject();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 String VN = String.valueOf(jComboBox1.getSelectedItem());
    num = Integer.parseInt(VN);
     switch(num){
         case 3:
     jRadioButton3.setEnabled(true);        
     jRadioButton4.setEnabled(false);
     jRadioButton5.setEnabled(false);
     jRadioButton6.setEnabled(false);
     jRadioButton12.setEnabled(false);
     jRadioButton13.setEnabled(false);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
         
         case 4:
     jRadioButton4.setEnabled(true);        
     jRadioButton5.setEnabled(false);
     jRadioButton6.setEnabled(false);
     jRadioButton12.setEnabled(false);
     jRadioButton13.setEnabled(false);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 5:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(false);
     jRadioButton12.setEnabled(false);
     jRadioButton13.setEnabled(false);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 6:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(false);
     jRadioButton13.setEnabled(false);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 7:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(true);
     jRadioButton13.setEnabled(false);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 8:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(true);
     jRadioButton13.setEnabled(true);
     jRadioButton14.setEnabled(false);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 9:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(true);
     jRadioButton13.setEnabled(true);
     jRadioButton14.setEnabled(true);
     jRadioButton15.setEnabled(false);
     jRadioButton16.setEnabled(false);
        break;
        
        case 10:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(true);
     jRadioButton13.setEnabled(true);
     jRadioButton14.setEnabled(true);
     jRadioButton15.setEnabled(true);
     jRadioButton16.setEnabled(false);
        break;
        
        case 11:
     jRadioButton4.setEnabled(true); 
     jRadioButton5.setEnabled(true);
     jRadioButton6.setEnabled(true);
     jRadioButton12.setEnabled(true);
     jRadioButton13.setEnabled(true);
     jRadioButton14.setEnabled(true);
     jRadioButton15.setEnabled(true);
     jRadioButton16.setEnabled(true);
        break;
     }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
           
        for (int i=0;i<num;i++){
            
            
             double e=(Vertices[i][0])*Math.toRadians(Double.parseDouble(jTextField8.getText()));
       double f=(Vertices[i][1])*Math.toRadians(Double.parseDouble(jTextField9.getText()));
            double xn = 0; 
            double yn = 0;
            Vertices[i][0] = (int)Math.round(xn) + Vertices[i][0]+(int)f;
            Vertices[i][1] = (int)Math.round(yn) + Vertices[i][1]+(int)e;
        
        }
        DrawObject();
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      double a = Math.toRadians(Double.parseDouble(jTextField1.getText()));
       double b = Math.toRadians(Double.parseDouble(jTextField3.getText()));
       double c = Math.toRadians(Double.parseDouble(jTextField5.getText()));
       double d = Math.toRadians(Double.parseDouble(jTextField6.getText()));
       
       double j=Integer.parseInt(jTextField10.getText());
     
           
        for (int i=0;i<num;i++){
            
            
         
         double xn = a*(Vertices[i][0])  + b*(Vertices[i][1])+(int)j;
            double yn = c*(Vertices[i][0])  + d*(Vertices[i][1])+(int)j;
            Vertices[i][0] = (int)Math.round(xn) + Vertices[i][0];
            Vertices[i][1] = (int)Math.round(yn) + Vertices[i][1];
        
        }
        DrawObject();   
    }//GEN-LAST:event_jButton6ActionPerformed

    public void DrawObject(){
    Graphics g = jPanel1.getGraphics();
    g.setColor(Color.WHITE);
    g.fillRect(0, 0, jPanel1.getWidth(),jPanel1.getHeight());
    for (int i=0;i<num;i++){
    int x1 = Vertices[i][0]+cX;
    int y1 = cY-Vertices[i][1];
    g.setColor(Color.red);
    g.fillOval(x1-4, y1-4, 8, 8);
    g.setColor(Color.black);
    g.drawString(String.valueOf(i+1), x1-3, y1-6);
    int x2,y2;
    if(i<num-1){
    x2 =Vertices[i+1][0]+cX;
    y2 =cY-Vertices[i+1][1];
    }else{
    x2 = Vertices[0][0]+cX;
    y2 = cY-Vertices[0][1];
           
    }
    g.drawLine(x1, y1, x2, y2);
    }
    
}
    
    
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
